### ISSUE TITLE
Clear Steps

### ISSUE THREAD

**Issue by khushalcolab** [DerekGloudemans/curvilinear-homography#1]
Can you update readme with steps to run this code with come examples.

**Comment by DerekGloudemans** [comment]
No, sorry. This repository is deprecated. You can look at 

https://github.com/DerekGloudemans/i24_rcs

for a still under construction version. I recommend to run `curvilinear_sandbox.py` which implements the basic spline-based coordinate system. The rest of the implementation details are fairly project specific (i.e. are specific to the I24 MOTION system).
